# Load the LSFB_ISOL dataset

In [1]:
import pandas as pd
from os import path
from lsfb_dataset.datasets.lsfb_isol.landmarks import LSFBIsolLandmarks
from lsfb_dataset.datasets.lsfb_isol.config import LSFBIsolConfig

import numpy as np

root_dir = '/home/jfink/Documents/unamur/signLanguage/Data/lsfb_isol'

load_config = LSFBIsolConfig(root_dir, lemmes_nb=10, split="mini_sample")
isolLoader = LSFBIsolLandmarks(config = load_config)

print(len(isolLoader))

for X, y ,m in isolLoader:
    print("Sequence : ")
    print(X)

    print("Target :")
    print(y)

    print("Mask : ")
    print(m)



---------- LSFB ISOL DATASET
LSFBIsolConfig(root='/home/jfink/Documents/unamur/signLanguage/Data/lsfb_isol', landmarks=['pose', 'hand_left', 'hand_right'], lemmes_nb=10, lemme_list_path='/home/jfink/Documents/unamur/signLanguage/Data/lsfb_isol/lemmes.csv', videos_list_path='/home/jfink/Documents/unamur/signLanguage/Data/lsfb_isol/clips.csv', split='mini_sample', sequence_max_length=50, padding=True, return_mask=True, mask_value=0)
Loading features (pose, hand_left, hand_right) and labels for each isolated sign...


100%|██████████| 10/10 [00:00<00:00, 111.29it/s]

----------
loading time: 0:00:00.112099
10
Sequence : 
[[0.5349074  0.32204863 0.5537894  ... 0.6739415  0.4257482  0.683168  ]
 [0.5332042  0.3222923  0.55184203 ... 0.6727034  0.42858315 0.6798511 ]
 [0.5316967  0.32288063 0.5501546  ... 0.67946774 0.4332824  0.68325055]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]
Target :
3
Mask : 
[1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0]
Sequence : 
[[0.43452203 0.358161   0.43366313 ... 0.4924257  0.36460438 0.50286067]
 [0.43522    0.3564623  0.43415338 ... 0.49180692 0.3711084  0.50510323]
 [0.4350387  0.3532616  0.4339971  ... 0.48937282 0.38103804 0.50474274]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.       

In [1]:
from json import load
import pandas as pd
from os import path
from lsfb_dataset.datasets.lsfb_isol.landmarks_generator import LSFBIsolLandmarksGenerator
from lsfb_dataset.datasets.lsfb_isol.config import LSFBIsolConfig
import numpy as np

root_dir = '/home/jfink/Documents/unamur/signLanguage/Data/lsfb_isol'

load_config = LSFBIsolConfig(root_dir, lemmes_nb=10, split="mini_sample")
isolLoader = LSFBIsolLandmarksGenerator(config= load_config)

print(len(isolLoader))

for X, y ,m in isolLoader:
    print("Sequence : ")
    print(X)

    print("Target :")
    print(y)

    print("Mask : ")
    print(m)



LSFBIsolConfig(root='/home/jfink/Documents/unamur/signLanguage/Data/lsfb_isol', landmarks=['pose', 'hand_left', 'hand_right'], lemmes_nb=10, lemme_list_path='/home/jfink/Documents/unamur/signLanguage/Data/lsfb_isol/lemmes.csv', videos_list_path='/home/jfink/Documents/unamur/signLanguage/Data/lsfb_isol/clips.csv', split='mini_sample', sequence_max_length=50, padding=True, return_mask=True, mask_value=0)
10
Sequence : 
[[0.5349074  0.32204863 0.5537894  ... 0.6739415  0.4257482  0.683168  ]
 [0.5332042  0.3222923  0.55184203 ... 0.6727034  0.42858315 0.6798511 ]
 [0.5316967  0.32288063 0.5501546  ... 0.67946774 0.4332824  0.68325055]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]
Target :
3
Mask : 
[1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0]
Sequence : 
[