# Load the LSFB_ISOL dataset

In [6]:
import pandas as pd
from os import path
from lsfb_dataset.datasets.lsfb_isol.landmarks import LSFBIsolLandmarks
import numpy as np

root_dir = '/home/jfink/Documents/unamur/signLanguage/Data/lsfb_isol'

isolLoader = LSFBIsolLandmarks(root_dir, lemmes_nb=10, split="mini_sample")

print(len(isolLoader))

for X, y ,m in isolLoader:
    print("Sequence : ")
    print(X)

    print("Target :")
    print(y)

    print("Mask : ")
    print(m)



---------- LSFB ISOL DATASET
97471
10
Loading features (pose, hand_left, hand_right) and labels for each isolated sign...


100%|██████████| 10/10 [00:00<00:00, 85.96it/s]

----------
loading time: 0:00:00.478234
10
Sequence : 
[[0.5349074  0.32204863 0.5537894  ... 0.6739415  0.4257482  0.683168  ]
 [0.5332042  0.3222923  0.55184203 ... 0.6727034  0.42858315 0.6798511 ]
 [0.5316967  0.32288063 0.5501546  ... 0.67946774 0.4332824  0.68325055]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]
Target :
3
Mask : 
[1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0]
Sequence : 
[[0.43452203 0.358161   0.43366313 ... 0.4924257  0.36460438 0.50286067]
 [0.43522    0.3564623  0.43415338 ... 0.49180692 0.3711084  0.50510323]
 [0.4350387  0.3532616  0.4339971  ... 0.48937282 0.38103804 0.50474274]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.       

In [1]:
import pandas as pd
from os import path
from lsfb_dataset.datasets.lsfb_isol.landmarks_generator import LSFBIsolLandmarksGenerator
import numpy as np

root_dir = '/home/jfink/Documents/unamur/signLanguage/Data/lsfb_isol'

isolLoader = LSFBIsolLandmarksGenerator(root_dir, lemmes_nb=10, split="mini_sample")

print(len(isolLoader))

for X, y ,m in isolLoader:
    print("Sequence : ")
    print(X)

    print("Target :")
    print(y)

    print("Mask : ")
    print(m)



10
Unnamed: 0                                                 7261
filename                     CLSFBI1518A_S035_B_11924_11933.mp4
lemme                                                 DIFFERENT
class                                                         3
video         videos/_DIFFERENT_/CLSFBI1518A_S035_B_11924_11...
pose          features/landmarks/_DIFFERENT_/pose/CLSFBI1518...
hands         features/landmarks/_DIFFERENT_/hands/CLSFBI151...
Name: 7261, dtype: object
Sequence : 
[[0.5349074  0.32204863 0.5537894  ... 0.6739415  0.4257482  0.683168  ]
 [0.5332042  0.3222923  0.55184203 ... 0.6727034  0.42858315 0.6798511 ]
 [0.5316967  0.32288063 0.5501546  ... 0.67946774 0.4332824  0.68325055]
 ...
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]
 [0.         0.         0.         ... 0.         0.         0.        ]]
Target :
3
Mask : 
[1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0